name: Running PyTests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  basic-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install postgres
        run: sudo apt-get -y update && sudo apt-get install postgresql
      - name: Install virtual enviroment
        run: pip install --user pipenv
      - name: Instal requirements
        run: pipenv install \ pipenv install --dev \ pipenv run python manage.py recreate_db
      - name: Start Pipenv
        run: pipenv shell
